### ISSUE TITLE
New Addon - Actions bar setup

### ISSUE THREAD

**Issue by HussonAxel** [Saaappi/addon-ideas#1]
Hello, I don't know if it's possible with what Blizzard offers, but is it possible to assign each spell to a particular shortcut? 
For example, in the addon management, I assign the key 1 to, idk Fireball as a mage, and when i login as a mage it retrieves the information from my spell bars and automatically sets the Fireball spell to 1? 
Thanks :)

**Comment by Saaappi** [comment]
Hey @HussonAxel,

Thanks for the idea! I think what you're describing is [Action Bar Profiles](https://github.com/rhodan412/wow-action-bar-profiles). Take a look and let me know if that addon will suit your needs.
